// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	CSGetuserReq
	CSGetuserRsp
*/
package protos

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CSGetuserReq struct {
	Uid              *int32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSGetuserReq) Reset()         { *m = CSGetuserReq{} }
func (m *CSGetuserReq) String() string { return proto.CompactTextString(m) }
func (*CSGetuserReq) ProtoMessage()    {}

func (m *CSGetuserReq) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type CSGetuserRsp struct {
	Uid              *int32  `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Age              *int32  `protobuf:"varint,3,req,name=age" json:"age,omitempty"`
	City             *string `protobuf:"bytes,4,req,name=city" json:"city,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CSGetuserRsp) Reset()         { *m = CSGetuserRsp{} }
func (m *CSGetuserRsp) String() string { return proto.CompactTextString(m) }
func (*CSGetuserRsp) ProtoMessage()    {}

func (m *CSGetuserRsp) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *CSGetuserRsp) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CSGetuserRsp) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *CSGetuserRsp) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func init() {
}
